#!/usr/bin/env sh

set -o errexit

antlr -Dlanguage=Python3 solidity-antlr4/Solidity.g4 -o src -visitor
mv src/solidity-antlr4/* src/solidity_antlr4
rm -rf src/solidity-antlr4

touch src/solidity_antlr4/__init__.py
touch src/solidity_antlr4/__AUTOGENERATED__
